"use client";

import { useCallback, useEffect, useState } from "react";
import {
  ChevronLeft,
  ChevronRight,
  Check,
  Copy,
  FileText,
  Loader2,
} from "lucide-react";

const ACCENT = "#303380";
const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

type TeacherOption = { id: string; name: string };

type StoredReport = {
  id: string;
  teacherId: string;
  teacherName: string;
  studentId: string;
  studentName: string;
  subject: string;
  text: string;
  createdAt: string;
};

type WeekGroup = {
  weekStart: string;
  weekLabel: string;
  reports: StoredReport[];
};

function ReportCard({ report }: { report: StoredReport }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(report.text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // ignore
    }
  };

  return (
    <div className="rounded-lg border border-slate-200 bg-white p-3 shadow-sm">
      <div className="mb-2 flex items-start justify-between gap-2">
        <div className="min-w-0">
          <div className="truncate text-sm font-semibold text-gray-900">
            {report.studentName}
          </div>
          <div className="truncate text-xs text-slate-500">
            {report.subject}
            {!report.teacherName ? null : ` · ${report.teacherName}`}
          </div>
        </div>
        <button
          type="button"
          onClick={copy}
          className="inline-flex shrink-0 items-center gap-1 rounded border border-slate-200 bg-white px-2 py-1 text-xs font-medium text-gray-700 hover:bg-slate-50"
        >
          {copied ? (
            <Check className="h-3.5 w-3.5" />
          ) : (
            <Copy className="h-3.5 w-3.5" />
          )}
          {copied ? "Copied" : "Copy"}
        </button>
      </div>
      <textarea
        readOnly
        value={report.text}
        onFocus={(e) => e.currentTarget.select()}
        className="h-36 w-full resize-none rounded-lg border border-slate-200 bg-slate-50 p-2 text-sm leading-relaxed text-gray-800 outline-none"
      />
    </div>
  );
}

export default function BossReportsPage() {
  const today = new Date();
  const [year, setYear] = useState(today.getFullYear());
  const [month, setMonth] = useState(today.getMonth());
  const [teacherId, setTeacherId] = useState("");
  const [teachers, setTeachers] = useState<TeacherOption[]>([]);
  const [weeks, setWeeks] = useState<WeekGroup[]>([]);
  const [loading, setLoading] = useState(true);
  const [openWeek, setOpenWeek] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({
        year: String(year),
        month: String(month + 1),
      });
      if (teacherId) params.set("teacherId", teacherId);
      const res = await fetch(`/api/boss/reports?${params}`);
      const data = await res.json();
      if (res.ok) {
        setTeachers(data.teachers ?? []);
        const w: WeekGroup[] = data.weeks ?? [];
        setWeeks(w);
        setOpenWeek(w[0]?.weekStart ?? null);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  }, [year, month, teacherId]);

  useEffect(() => {
    load();
  }, [load]);

  const prevMonth = () => {
    setOpenWeek(null);
    if (month === 0) {
      setMonth(11);
      setYear((y) => y - 1);
    } else setMonth((m) => m - 1);
  };
  const nextMonth = () => {
    setOpenWeek(null);
    if (month === 11) {
      setMonth(0);
      setYear((y) => y + 1);
    } else setMonth((m) => m + 1);
  };

  const totalReports = weeks.reduce((n, w) => n + w.reports.length, 0);

  return (
    <div className="p-4 sm:p-6 lg:p-8">
      <div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Weekly reports</h1>
          <p className="mt-1 text-sm text-gray-600">
            Stored parent reports generated by teachers (view & copy only)
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <select
            value={teacherId}
            onChange={(e) => {
              setTeacherId(e.target.value);
              setOpenWeek(null);
            }}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm"
          >
            <option value="">All teachers</option>
            {teachers.map((t) => (
              <option key={t.id} value={t.id}>
                {t.name}
              </option>
            ))}
          </select>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={prevMonth}
              className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 bg-white shadow-sm hover:bg-slate-50"
            >
              <ChevronLeft className="h-4 w-4" />
            </button>
            <span className="min-w-[140px] text-center text-sm font-semibold text-gray-900">
              {MONTHS[month]} {year}
            </span>
            <button
              type="button"
              onClick={nextMonth}
              className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 bg-white shadow-sm hover:bg-slate-50"
            >
              <ChevronRight className="h-4 w-4" />
            </button>
          </div>
        </div>
      </div>

      <div className="mb-4 inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-600 shadow-sm">
        <FileText className="h-4 w-4" style={{ color: ACCENT }} />
        {loading ? "Loading…" : `${totalReports} report${totalReports === 1 ? "" : "s"} in ${weeks.length} week${weeks.length === 1 ? "" : "s"}`}
      </div>

      {loading ? (
        <div className="flex items-center justify-center gap-2 py-20 text-sm text-slate-500">
          <Loader2 className="h-4 w-4 animate-spin" />
          Loading reports…
        </div>
      ) : weeks.length === 0 ? (
        <div className="rounded-xl border border-slate-200 bg-white py-20 text-center text-sm text-slate-500 shadow-sm">
          No stored reports for this month.
          <br />
          Teachers generate them from the schedule dashboard.
        </div>
      ) : (
        <div className="space-y-3">
          {weeks.map((week) => {
            const isOpen = openWeek === week.weekStart;
            return (
              <div
                key={week.weekStart}
                className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"
              >
                <button
                  type="button"
                  onClick={() =>
                    setOpenWeek(isOpen ? null : week.weekStart)
                  }
                  className="flex w-full items-center justify-between gap-3 px-4 py-3 text-left hover:bg-slate-50"
                >
                  <div>
                    <div className="font-semibold text-gray-900">
                      {week.weekLabel}
                    </div>
                    <div className="text-xs text-slate-500">
                      {week.reports.length} report
                      {week.reports.length === 1 ? "" : "s"}
                    </div>
                  </div>
                  <ChevronRight
                    className={`h-5 w-5 text-slate-400 transition ${isOpen ? "rotate-90" : ""}`}
                  />
                </button>
                {isOpen && (
                  <div className="grid gap-3 border-t border-slate-100 bg-slate-50/50 p-4 sm:grid-cols-2">
                    {week.reports.map((r) => (
                      <ReportCard key={r.id} report={r} />
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
